# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'Photo Flickr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Photo Flickr
	pod 'Kingfisher', '~> 7.0'

  target 'Photo FlickrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Photo FlickrUITests' do
    # Pods for testing
  end

end
